# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_master',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_master',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_comp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance1.Company_master')),
            ],
        ),
        migrations.CreateModel(
            name='User_attendance',
            fields=[
                ('user_att_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.CharField(blank=True, max_length=10, null=True)),
                ('ua_emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance1.Employee_master')),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('permission', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employee_master',
            name='emp_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance1.UserLogin'),
        ),
    ]
